name = "Evil Havoc"
author = "minecraftbossdj, Blista__Compact, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5483d1775567ca51933020e33f57a07e827f85ab5f59af3ec2b5b78abe1bdfe2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
