name = "Evil Havoc"
author = "minecraftbossdj, Blista__Compact, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3762e1e98d62017524a5856ed38f9fbf7d1a0fb4eb42f5a3c6a07312cab6e6cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
