name = "Evil Havoc"
author = "minecraftbossdj, Blista__Compact, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b7bc40b96dcec4ba4f96800adf08cbcf86b965c17c5099a37c44a05ea438de7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
